plugins:
  code_review_enabled: false
  code_review_api_username: ""
  code_review_pending_tag: "pending"
  code_review_approved_tag: "approved"
  code_review_followup_tag: "follow-up"
  code_review_github_webhook_secret: ""
  code_review_allow_self_approval:
    client: true
    default: false
