plugins:
  code_review_enabled: false
  code_review_github_repo: ""
  code_review_api_username: ""
  code_review_pending_category_id:
    hidden: true
    default: -1
  code_review_approved_category_id:
    hidden: true
    default: -1
  code_review_followup_category_id:
    hidden: true
    default: -1
